<?php

declare(strict_types=1);

namespace Maatify\RateLimiter\Config;

use Maatify\RateLimiter\Exception\RateLimiterException;

/**
 * Immutable secrets and environment scope used by the default composition.
 *
 * The outer key-generation and fingerprint-generation secrets are independent
 * inputs. Previous values represent at most one previous generation for their
 * respective concern and are never serialized or generated by this package.
 */
final readonly class RateLimiterConfig
{
    private string $keySecret;

    private string $fingerprintSecret;

    private string $environmentScope;

    private ?string $previousKeySecret;

    private ?string $previousFingerprintSecret;

    /**
     * Validate and retain the active and optional previous generation inputs.
     *
     * @param string $keySecret Active outer key-generation secret.
     * @param string $fingerprintSecret Active fingerprint-generation secret.
     * @param string $environmentScope Non-blank namespace included in derived keys.
     * @param ?string $previousKeySecret Optional previous outer key-generation secret.
     * @param ?string $previousFingerprintSecret Optional previous fingerprint-generation secret.
     * @throws RateLimiterException When any required or provided optional value is blank.
     */
    public function __construct(
        #[\SensitiveParameter]
        string $keySecret,
        #[\SensitiveParameter]
        string $fingerprintSecret,
        string $environmentScope,
        #[\SensitiveParameter]
        ?string $previousKeySecret = null,
        #[\SensitiveParameter]
        ?string $previousFingerprintSecret = null,
    ) {
        self::assertNotBlank($keySecret, 'Active key secret');
        self::assertNotBlank($fingerprintSecret, 'Active fingerprint secret');
        self::assertNotBlank($environmentScope, 'Environment scope');

        if ($previousKeySecret !== null) {
            self::assertNotBlank($previousKeySecret, 'Previous key secret');
        }

        if ($previousFingerprintSecret !== null) {
            self::assertNotBlank($previousFingerprintSecret, 'Previous fingerprint secret');
        }

        $this->keySecret = $keySecret;
        $this->fingerprintSecret = $fingerprintSecret;
        $this->environmentScope = $environmentScope;
        $this->previousKeySecret = $previousKeySecret;
        $this->previousFingerprintSecret = $previousFingerprintSecret;
    }

    /**
     * Return the active outer key-generation secret.
     */
    public function keySecret(): string
    {
        return $this->keySecret;
    }

    /**
     * Return the active fingerprint-generation secret.
     */
    public function fingerprintSecret(): string
    {
        return $this->fingerprintSecret;
    }

    /**
     * Return the environment namespace included in derived keys.
     */
    public function environmentScope(): string
    {
        return $this->environmentScope;
    }

    /**
     * Return the optional previous outer key-generation secret.
     */
    public function previousKeySecret(): ?string
    {
        return $this->previousKeySecret;
    }

    /**
     * Return the optional previous fingerprint-generation secret.
     */
    public function previousFingerprintSecret(): ?string
    {
        return $this->previousFingerprintSecret;
    }

    private static function assertNotBlank(string $value, string $name): void
    {
        if (trim($value) === '') {
            throw new RateLimiterException("{$name} must not be empty or whitespace-only.");
        }
    }
}
